# **Решение 9 номера**


## **Оглавление:**
*   **Функция** **`set`**
*   **Функция** **`map`**
*   ***CSV - файлы***
*   **Чтение файла**
*   **Метод решени**я
*   **Домашнее задание**


В данной рабочей тетради мы познакомимся с чтением ***csv-файлов***, что нам пригодится и в дальнейшем для решения задач, а так же освоим функции **`map`** и **`set`**, что будет полезно для решения более сложных задач.

*`! Эта рабочая тетрадь поставляется вместе с предлагаемыми примерами csv файлов, поэтому убедитесь, что они находятся в той же папке на компьютере, что и этот блокнот. !`*

# **1. Функция *`set`* и множества**

## **Определение множества и его свойства**

Итак, функция *`set`* создает множество элементов из итерируемого объекта (список, строка, кортеж и прочие).

И прежде, чем идти дальше, необходимо разобраться с тем, что такое множество.

***Множество (set)*** - это изменяемый набор уникальных и неупорядоченных элемнтов.

***Свойства множеств:***
- **Уникальность:** *каждый элемент входит в множество ровно один раз, если попробовать добавить дубликат, то python его проигнорирует*
- **Неупорядоченность:** *у элементов множества нет порядкового номера*
- **Изменяемость:** *множество можно пополнять, а также удалять из него элементы*

## **Создание множеств:**

1. Создать множество можно с помощью фигурных скобок и перечисления элементов внутри них через запятую:

In [1]:
example = {1, 2, 3, 3} # Тут находится множество
# обрати внимание, что есть дубликат
print(example) # При выводе мы увидим, что дубликат был проигнорирован

{1, 2, 3}

2. С помощью функции *`set()`* и переданного в нее итерируемого объекта:

In [2]:
array = [1, 2, 3, 3] # Тут мы просто создаем список, содержащий в себе дубликаты
my_set = set(array) # Передаем этот список внутрь функции set и созданное множество запоминается в переменную my_set
print(my_set) # При выводе мы увидим, что дубликат был проигнорирован

{1, 2, 3}

In [3]:
string = 'aaabbc' # Создаем обычную строку
my_set = set(string) # Создаем множество из элементов
print(my_set)

{'b', 'a', 'c'}

Тут важно сделать замечание: **порядок внутри множества может быть произвольным**, поэтому **не** стоит считать, что происходит сортировка по алфавиту/от меньшего к большему.


Это делает возможным сравнивать множества без внимания на порядок элементов в нем, как это было бы в списке или строке:

In [4]:
print([1, 2, 3] == [1, 3, 2]) # Здесь мы сравниваем два списка с одинаковым составом, но разным порядком
print(set([1, 2, 3]) == set([1, 3, 2])) # Здесь происходит сравнение двух множеств, в котором мы закономерно получаем True

False
True

# **2. Функция *`map`***

***Синтаксис:***
`map(func, obj)`


Функция map необходима для того, чтобы применить функцию *`func`*, стоящую на первом месте к каждому элементу итерируемого множества *`obj`* (строка, список и подобные).

***Пример использования:***

Предположим, что у нас есть список, состоящий из строк, которые нужно перевести из строки в целые числа, используя функцию *`int`*

In [5]:
array = ['1', '2', '3', '4'] # Список, состоящий из строк
new_array = map(int, array) # Применяем с помощью map функцию int ко всем элементам array
print(new_array) # Выводим результат

<map object at 0x78a6c4f576d0>

И тут получается странное: мы видим какой то объект, какой-то код, что нас не очень устраивает. И тут возникает особенность этой функции - результатом работы является объект - итератор. Что это такое, нас не волнует, поэтому просто запоминаем следующее - преобразовать итератор необходимо в подходящий нам вид (список, множество, кортеж)

Поправим приведенный выше код с указанным замечанием:

In [6]:
array = ['1', '2', '3', '4'] # Список, состоящий из строк
new_array = list(map(int, array)) # Применяем с помощью map функцию int ко всем элементам array
print(new_array) # Выводим результат

[1, 2, 3, 4]

Еще парочка примеров на работу с функцией *`map`*:

In [8]:
string = '123123' # В случае работы со строкой каждым элемнтом, на который будет применяться функция из map, будет каждый элемент строки
lst = list(map(int, string))
print(lst)

[1, 2, 3, 1, 2, 3]

In [9]:
def pw(n):
  return n ** 2
# Определили функцию, которая возводит число в квадрат

array = [10, 11, 12]
new_array = list(map(pw, array)) # Передаем ее в качестве первого аргумента внутри map
print(new_array)

[100, 121, 144]

# **3. CSV - файлы**

***CSV (comma-separated values)*** - формат хранения таблиц (*xls*, например), в котором каждое значение отделяется от соседнего с помощью одного и того же знака разделения.

Пример вида *`csv - файла`*:

In [ ]:
1,2,3,4
5,6,7,8
9,10,11,12

14O

Как вы можете заметить, каждое число отделяется от соседнего запятой (но это может быть и любой другой сивмол, который называется delimiter).

# **4. Чтение файлов**

Для чтения ***csv - файлов*** нам нужен минимальный инструментарий: функция `open`, библиотека `csv` и все.

Первым делом, убедитесь, что вы знаете полный путь до файла (в случае, если читаемый файл находится в одной папке с программой, то достаточно знать лишь его название). Затем, используя функцию `open` мы открываем файл в переменную, и читаем его функцией `reader` из модуля `csv`, указав действующий *delimiter* (узнать его можно просто открыв файл и посмотрев на таблицу внутри него).

Файлы, который подаются с этой рабочей тетрадью находятся внутри каталога *`data`*, поэтому для доступа к ним в путь от файла нужно добавить репозиторий с соответствующим названием. Если это не совсем понятно, прошу обратить внимание на следующий пример, где все будет пояснено:

In [1]:
import csv # Для использование reader'а необходимо импортировать модуль csv

file = open('data/test.csv') # Здесь путь до файла содержит папку data,
# так как всей даты для тетради находятся в ней

data = csv.reader(file, delimiter=',') # Здесь мы считываем данные из открытого файла,
# указав разделитель как запятую

for row in data: # Теперь мы можем перебрать строки из файла
  print(row) # В таком цикле, каждый объект будет одной строкой из открытого файла

['1', '2', '3', '4']
['5', '6', '7', '8']
['10', '11', '12', '13']
['14', '15', '16', '17']

# **5. Методы решения**

Рассмотрим основной метод решения 9ого номера на трех примерах разной сложности.

----------------

## **1 пример:**

### **Условие:**

***Откройте файл электронной таблицы, содержащей в каждой строке пять натуральных чисел. Определите количество строк таблицы, содержащих числа, для которых выполнены оба условия:***

- *в строке все числа различны;*

- *удвоенная сумма максимального и минимального чисел строки не больше суммы оставшихся трёх её чисел.*

***В ответе запишите только число.***

----------------

Итак, в первую очередь, конечно, нам нужно открыть файл. Для этой задачи он называется example_1.csv. Считать каждую из строчек этого файла, перевести их из строк в целые числа, проверить, что все числа различны множеством и проверить второе условие простой математической операцией. Не волнуйся, пояснения будут по коду.

In [2]:
import csv # Импортируем модуль csv

file = open('data/example_1.csv') # Открываем файл
data = csv.reader(file, delimiter=',') # Читаем файл, указав разделитель запятую

count = 0 # Нам нужно узнать количество строк, поэтому мы создаем счетчик

for row in data: # Перебираем все строки таблицы
  row = list(map(int, row)) # Так как при чтении мы получаем список, состоящий из строк, нам нужно применить функцию int к каждому элементу такого списка
  if len(set(row)) == len(row): # Если длина множества совпадает с длиной самого списка, значит дубликатов в нем нет
    mx = max(row) # Берем максимальный элемент строки
    mn = min(row) # Берем минимальный элемент строки
    if (mx + mn) * 2 <= (sum(row) - mn - mx): # Проверяем вторую часть условия
      count = count + 1 # Если выполняются оба условия, то увеличиваем счетчик на один

print(count) # Получаем ответ

607

Идем дальше:


----------------

## **2 пример:**

### **Условие:**

***В каждой строке электронной таблицы записаны шесть натуральных чисел.
Определите количество строк таблицы, содержащих числа, для которых одновременно выполнены все следующие условия:***

- *минимальное число встречается в строке ровно один раз;*

- *хотя бы одно число в строке повторяется более одного раза;*

- *максимальное число в строке превышает среднее арифметическое остальных пяти чисел этой строки более чем в три раза.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------

Пояснения снова будут по ходу кода, поэтому не волнуйся, все будет понятно (надеюсь).

In [3]:
import csv # Импортируем модуль csv

file = open('data/example_2.csv') # Открываем файл
data = csv.reader(file, delimiter=',') # Читаем файл, указав разделитель запятую

count = 0 # Нам нужно узнать количество строк, поэтому мы создаем счетчик

for row in data: # Перебираем все строки таблицы
  row = list(map(int, row)) # Так как при чтении мы получаем список, состоящий из строк, нам нужно применить функцию int к каждому элементу такого списка
  mn = min(row) # Берем минимальный элемент строки
  mx = max(row) # Берем максимальный элемент строки
  if row.count(mn) == 1: # Проверяем, что в списке минимальный элемент ровно 1
    if len(set(row)) != len(row): # Если длина множества не совпадает с длиной списка, значит в списке есть дубликаты (2 условие)
      if mx > ((sum(row) - mx) / 5) * 3: # Проверяем оставшееся условие задачи
        count += 1 # Учитываем каждую подходящую строку

print(count) # Выводим ответ

49

И последний пример:


----------------

## **3 пример:**

### **Условие:**

***Откройте файл электронной таблицы, содержащей в каждой строке шесть натуральных чисел.
Определите количество строк таблицы, содержащих числа, для которых выполнены оба условия:***

- *в строке только одно число повторяется ровно два раза, остальные числа различны;*

- *среднее арифметическое неповторяющихся чисел строки не больше суммы повторяющихся чисел.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------

Пояснения снова будут по ходу кода, поэтому не волнуйся, все будет понятно (надеюсь).

In [19]:
import csv

file = open('data/example_3.csv')
data = csv.reader(file, delimiter=',')

count = 0

for row in data:
  row = list(map(int, row))
  povt = [i for i in row if row.count(i) > 1] # Создаем список повторяющихся чисел, т е добавляем i только в том случае
  # если оно встречается в списке больше одного раза
  nepovt = [i for i in row if row.count(i) == 1] # Создаем список неповторяющихся чисел, т е добавляем i только в том случае
  # если оно встречается в списке ровно один раз
  if len(povt) == 2 and len(set(povt)) == 1: # Одно число повторяется дважды, значит список повторов должен состоять из
  # двух элементов и множество этого списка содержит ровно один элемент (то число, которое повторяется дважды)
    if sum(nepovt) / len(nepovt) <= sum(povt):
      count += 1

print(count)

2241

# **6. Домашнее задание**

Файл для задачи находится в папке data и называется `dz_1.csv`. Для первой задачи я покажу как необходимо считывать данные, остальные задачи будут иметь пустые блоки с кодом.


----------------

## **1 задача:**

### **Условие:**

***Откройте файл электронной таблицы, содержащей в каждой строке четыре натуральных числа.
Определите количество строк таблицы, содержащих числа, для которых выполнены оба условия:***

- *наименьшее из четырёх чисел более чем в шесть раз меньше суммы трёх других;*

- *произведение наибольшего и наименьшего числа больше произведения оставшихся чисел*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------
Файл: dz_1.csv

In [ ]:
import csv

file = open('data/dz_1.csv')
data = csv.reader(file, delimiter=',')

# Введите решение здесь

Здесь уже необходимо полное решение привести самостоятельно


----------------

## **2 задача:**

### **Условие:**

***Откройте файл электронной таблицы, содержащей в каждой строке семь натуральных чисел. Определите количество строк таблицы, содержащих числа, для которых выполнены оба условия:***

- *среди семи чисел совпадают ровно четыре числа;*

- *среднее значение повторяющихся чисел больше, чем среднее арифметическое неповторяющихся чисел строки.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------
Файл: dz_2.csv

In [ ]:


# Введите решение здесь

Здесь уже необходимо полное решение привести самостоятельно


----------------

## **3 задача:**

### **Условие:**

***Откройте файл электронной таблицы, содержащей в каждой строке шесть натуральных чисел.
Определите количество строк таблицы, для чисел которых одновременно выполнены все следующие условия:***

- *в строке есть повторяющиеся числа;*

- *максимальное число в строке не повторяется;*

- *сумма всех повторяющихся чисел в строке меньше максимального числа этой строки. При подсчёте суммы повторяющихся чисел каждое число учитывается столько раз, сколько оно встречается.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------
Файл: dz_3.csv

In [ ]:


# Введите решение здесь

Здесь уже необходимо полное решение привести самостоятельно


----------------

## **4 задача:**

### **Условие:**

***В каждой строке электронной таблицы записаны пять натуральных чисел.
Определите, сколько в таблице строк, для которых выполнены следующие условия:***

- *все числа в строке различны;*

- *чётных чисел больше, чем нечётных;*

- *cумма чётных чисел меньше суммы нечётных.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------
Файл: dz_4.csv

In [ ]:


# Введите решение здесь

Здесь уже необходимо полное решение привести самостоятельно


----------------

## **5 задача:**

### **Условие:**

***В каждой строке электронной таблицы записаны шесть натуральных чисел. Определите, сколько в таблице строк, для которых выполнены следующие условия:***

- *в строке встречается ровно четыре различных числа; два из них по два раза, два — по одному;*

- *сумма повторяющихся чисел (без учёта повторений, то есть каждое число входит в сумму один раз) меньше суммы неповторяющихся.*

***В ответе запишите число — количество строк, для которых выполнены эти условия.***

----------------
Файл: dz_5.csv

In [ ]:


# Введите решение здесь